// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVEW9XEw-EqsZ09wSxRh686njQrxsrwKs',
    appId: '1:804149413178:web:6db4cffb41f3390ab97c03',
    messagingSenderId: '804149413178',
    projectId: 'alpha-227bc',
    authDomain: 'alpha-227bc.firebaseapp.com',
    storageBucket: 'alpha-227bc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEe4SevvUl61ZA-PfHg-p5qm6gCDBY_b0',
    appId: '1:804149413178:android:0acd2e62f8a6bfa2b97c03',
    messagingSenderId: '804149413178',
    projectId: 'alpha-227bc',
    storageBucket: 'alpha-227bc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBu2ZKLp7YthqfsTCgF1Xj3YMAakuFGIt8',
    appId: '1:804149413178:ios:2d00cc0ee538e076b97c03',
    messagingSenderId: '804149413178',
    projectId: 'alpha-227bc',
    storageBucket: 'alpha-227bc.appspot.com',
    iosClientId: '804149413178-l5jt7ophu495v5a87mn3uop38g2nicbg.apps.googleusercontent.com',
    iosBundleId: 'com.playdata.test',
  );
}
